# NumPy - Numerical Python Library

In [1]:
#Import Numpy Library

import numpy as np

In [2]:
#create simple array from the list

arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
#diamension of the array

print(arr.ndim)

2


In [4]:
#shape of the array

print(arr.shape)

(2, 4)


In [5]:
#diamension of the array

print(type(arr))

<class 'numpy.ndarray'>


In [6]:
#diamension of the array

print(arr.data)

# Random Number Generator using numpy

In [3]:
from numpy import random
x= random.randint(100)
print(x)

22


In [8]:
#Generate Random Float

x= random.rand()
print(x)

0.6538887333987534


In [9]:
#3.	Generate Random Array

from numpy import random
x= random.randint(100, size=(5))
print(x)

[14 61 78 76 23]


In [10]:
#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100

from numpy import random
x= random.randint(100, size=(3, 5))
print(x)


[[ 2 76 87 96  7]
 [88 69 33 20  8]
 [ 1 60 81  3 15]]


# 2.4 PRACTICAL:  Creating scalars in Numpy

In [14]:
#numpy.asscaler()

import numpy as np

in_arr = np.array([8])

print("input array is ", in_arr)

out_scalar = np.asscalar(in_arr)
print("output scalar from input array ", out_scalar)


input array is  [8]
output scalar from input array  8


<ipython-input-14-8934cba7361c>:9: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
  out_scalar = np.asscalar(in_arr)


# 2.5 PRACTICAL:  Creating Vector in Numpy

In [17]:
#import numpy

import numpy as np

#creating 1-D list
list1 = [1, 2, 3]

#creating 1-D list vertical

list2 = [[10],
        [20],
        [30]]

#create vector1

vector1 =  np.array(list1)
vector2 = np.array(list2)

print("Horizontal Vector")
print(vector1)

print("------------------")

print("Vectical Vector")
print(vector2)



Horizontal Vector
[1 2 3]
------------------
Vectical Vector
[[10]
 [20]
 [30]]


# 2.6 PRACTICAL Creating Matrix in Numpy

In [18]:
import numpy as np

a=np.matrix('1 2; 3 4')
print("via string input : \n", a, "\n\n")

#array-like input
b = np.matrix([[5, 6, 7], [4, 6]])
print("via array-like input :\n", b)

via string input : 
 [[1 2]
 [3 4]] 


via array-like input :
 [[list([5, 6, 7]) list([4, 6])]]


C:\ProgramData\Anaconda3\lib\site-packages\numpy\matrixlib\defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr = N.array(data, dtype=dtype, copy=copy)


# 2.7 PRACTICAL:  Matrix Multiplication in Numpy

In [19]:
import numpy as np

A = 5

B = [[6, 7],
      [8, 9]]
 
print(np.dot(A,B))

[[30 35]
 [40 45]]


In [20]:
import numpy as np

A = [[6, 7],
      [8, 9]]
      
B = [[1, 3],
      [5, 7]]

print(np.dot(A,B))

print("----------")

print(np.dot(B,A))

[[41 67]
 [53 87]]
----------
[[30 34]
 [86 98]]


# 2.8 PRACTICAL:  Measure of Central Tendency Using Numpy

In [21]:
import numpy as np

arr = np.array([[1,23,78], [98,60,75],[79,25,48]])
print(arr)

#min function
print(np.amin(arr))
#max function
print(np.amax(arr))


[[ 1 23 78]
 [98 60 75]
 [79 25 48]]
1
98


In [28]:
#2.	Finding Mean, Median, Standard Deviation and Variance in NumPy
a = np.array([5,6,7])
print(a)
print("mean of array a =",np.mean(a))
print("median of array a =",np.median(a))
print("standard deviation of array a =",np.std(a))
print("Variance of array a =",np.var(a))

[5 6 7]
mean of array a = 6.0
median of array a = 6.0
standard deviation of array a = 0.816496580927726
Variance of array a = 0.6666666666666666


# 2.9 PRACTICAL:  Percentile & Interquartile in Numpy

In [29]:
import numpy as np
data = [32, 36, 46, 47, 56, 69, 75, 79, 79, 88, 89, 91, 92,93, 96, 97,101,105,112,116]

#first quartile(Q1)

Q1 = np.median(data[:10])

#third Quartile
Q3 = np.median(data[10:])

#interquartile range

IQR = Q3-Q1

print(IQR)


34.0


# 2.10 PRACTICAL:  Array Broadcasting in Numpy

In [32]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])

a * b

array([2., 4., 6.])

In [33]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0

a * b

array([2., 4., 6.])